name: default
threshold: 0.5

by_task:
  binary_classification:
    primary: auc
    threshold: 0.5
    include:
      - acc
      - f1
      - recall
      - precision
      - mcc
      - auc
      - auc_pr
      - brier
  multiclass_classification:
    primary: f1_macro
    include:
      - acc
      - balanced_acc
      - f1_macro
      - f1_weighted
      - precision_macro
      - recall_macro
      - auc_ovr
  regression:
    primary: rmse
    include:
      - mse
      - rmse
      - mae
      - r2
      - explained_variance
